# Generated by Django 4.2.14 on 2024-07-16 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('deparment', models.CharField(max_length=50)),
                ('age', models.IntegerField(max_length=5)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
