# Generated by Django 4.2.14 on 2024-07-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='deparment',
            new_name='department',
        ),
        migrations.AlterField(
            model_name='employees',
            name='age',
            field=models.IntegerField(),
        ),
    ]
