# Generated by Django 4.2.14 on 2024-07-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_employees_city_employees_phone_employees_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='pincode',
            field=models.IntegerField(null=True),
        ),
    ]
